# -*- mode: python ; coding: utf-8 -*-
# This file is auto-generated by build_master.py. DO NOT EDIT.

import os

# Application information
APP_NAME = "ApexFlow"
VERSION = "5.3.0"

# Define required files and folders
data_files = [('../assets', 'assets'), ('../data', 'data'), ('../modules/default_settings.json', 'modules'), ('../docs', 'docs')]

# Required hidden imports
hidden_imports = ['PySide6.QtCore', 'PySide6.QtGui', 'PySide6.QtWidgets', 'PySide6.QtPrintSupport', 'PySide6.QtSvg', 'PyPDF2', 'fitz', 'PIL', 'PIL.Image', 'arabic_reshaper', 'bidi', 'bidi.algorithm', 'psutil', 'win32api', 'win32print', 'win32gui', 'pywintypes', 'json', 'pathlib', 'logging', 'threading', 'queue', 'tkinter']

# Excluded modules
excludes = ['matplotlib', 'numpy', 'scipy', 'pandas', 'jupyter', 'IPython', 'notebook', 'tornado', 'zmq']

# Analyze files
a = Analysis(
    ['../main.py'],
    pathex=[],
    binaries=[],
    datas=data_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
    optimize=0,
)

# Create PYZ file
pyz = PYZ(a.pure, a.zipped_data, cipher=None)

# Create executable file
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='../assets/icons/ApexFlow.ico',
    version_file=None,
)

# Collect all files
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name=APP_NAME,
)
